Remove student
chizuo/COMP586-Project pull request #15
Opened 2022-10-27 02:43 UTC by harshleen8

2022-10-27 19:27 UTC, chizuo requested changes
This is non-compiling code. If you require assistance in understanding how to implement this then reach out to your peers.

2022-10-27 19:27 UTC, chizuo commented on Models/Section.cs
> +        public bool removeStudent(Student student){
there is a lot wrong going on here @harshleen8

I would reach out to your teammates (@Brandon-CSUN & @Jacob-Asaad) if you need help because you should not be making pull requests for non-compiling code.

2022-10-28 03:45 UTC, harshleen8 commented on Models/Section.cs
> +        public bool removeStudent(Student student){
@chizuo , I am so sorry for doing such a blunder. I somehow lost the path, I have connected with @Brandon-CSUN and took his help in clarifying things and working on the same.

2022-10-28 17:12 UTC, chizuo requested changes
This is a lot better. Please read my feedback on 2 sections of the implementation

2022-10-28 17:12 UTC, chizuo commented on Models/Section.cs
> +                    break;
instead of breaking here, you could actually just return true;
which will cause you to leave the method and you wouldn't need to break.

2022-10-28 17:45 UTC, chizuo commented
be sure to pull since your PR is behind after merging @Brandon-CSUN PR

2022-10-28 18:29 UTC, Brandon-CSUN commented on Models/Section.cs
> +                    break;
Okay that's make a lot more sense, returns true if you found student in the enrollment.

2022-10-28 22:20 UTC, merged