removeSection Added
chizuo/COMP586-Project pull request #16
Opened 2022-10-27 05:26 UTC by Jacob-Asaad

removeSection method added in Person.cs 
This method allows the derived classes, Student & Professor the ability to remove a section from their schedule.
By unpacking the schedule, this method finds the day(s) that the section occurs and checks those days for the section's respective sectionNumber. If found, it'll remove the section from that day and continue on until the section is removed from each of its scheduled day(s).

2022-10-27 06:37 UTC, Jacob-Asaad commented
hello

2022-10-27 06:37 UTC, Jacob-Asaad commented
hello

2022-10-27 06:42 UTC, chizuo requested changes
Woops, I forgot to submit review. My bad

2022-10-27 19:46 UTC, chizuo commented
@Jacob-Asaad I'm good with the changes. @Brandon-CSUN had a comment that I told him to provide as a legitimate code review feedback to you. So I'll let him decide on when to merge this PR based on if he just wants to leave a non-change request review or not.

2022-10-27 19:47 UTC, chizuo approved these changes

2022-10-27 20:21 UTC, Brandon-CSUN commented on Models/Person.cs
> +                    if(sections.classSectionNumber==sectionCode){ //if that day contains the section number we want -> remove it, otherwise break, and check the next day (index)
You could clean up line 70 since sections.classSectionNumber already reference to the section number variable so you don't need to daisy chain line 62 sectionCode = sections.classSectionNumber. This will make you code look much cleaner and more readable for whoever is reading it.

2022-10-28 02:43 UTC, Brandon-CSUN commented on Models/Person.cs
> +                    if(sections.classSectionNumber==sectionCode){ //if that section contains the sectionNumber we want -> remove it and break out of the current dailySchedule, and check the next day
You could do this if(section.classSectionNumber==sections.classSectionNumber) which means if ( the section object's section number that was past thorugh is equal to one of the sections objects' section number in the daily schedule list).

2022-10-28 02:44 UTC, merged